language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - src/containers
script:
  - npm test --cover-package=components && coverage report
after_success:
  - npm test -- --coverage